### ISSUE TITLE
Issue with data edge_attr is None 

### ISSUE THREAD

**Issue by dgm2** [beabevi/ESAN#1]
Hello, Thanks for releasing the code.

I am getting an error in a few datasets (IMDB-B, PROTEINS) about edge_attr being None, as soon as this object is needed in the convolution.
Was this issue encountered before? or any possible suggestions?

Thanks

**Comment by beabevi** [comment]
Hello giame,

Can you be more specific on the configuration you are running?

**Comment by dgm2** [comment]
1) I have run data.py with the **edge_deletion** policy,  (also tried some other policies), as follows:
`data.py --dataset=PROTEINS --policies=edge_deleted`
Here it seems that edge_attr is already None, in the dataset, so this seems to cause the issue in the next point.
This script terminates successfully.

2) in the model, it is required edge_attr: https://github.com/beabevi/ESAN/blob/master/models.py#L186

I run as follows: (model=deepsets, also tried model=gnn)
`--dataset=PROTEINS --policy=edge_deleted --model=deepsets --gnn_type=gin`
At this point getting error for edge_attr being None

I am running locally with pytorch-geometric 1.7.2

**Comment by beabevi** [comment]
For the TUDatasets you must use `--gnn_type=originalgin`.
Indeed,  `--gnn_type=gin` uses `edge_attr` and it is used for `ogbg` datasets.

You can see which `gnn_type` is used for each dataset in the corresponding `yaml` file under `configs/`.

**Comment by dgm2** [comment]
Ah OK I was running with a wrong configuration. 
I was able to run with your suggestion. 
Thanks a lot!
